src/app.module.ts, src/config/body-size.config.ts, src/config/cors.config.ts, src/config/graceful-shutdown.config.ts, src/config/index.ts, src/config/json.middleware.ts, src/config/validator-container.config.ts, src/main.ts
Досега API-то поддържаше CORS чрез nginx конфигурация.
Има от време на време някои проблеми с това.
Също така при локална разработка едновременно на API-то и админа/резултатите това помага, защото преди нямаше CORS на localhost.
При deployment, CORS конфигурацията на nginx трябва да бъде изключен.
=> Config refactor

.github/workflows/codeql-analysis.yml
Пуска CodeQL интеграцията за GitHub, която сканира кода за проблеми в сигурността.
Ще се пуска автоматично всяка сутрин в 6:45 и ако засече проблем, ще изпрати автоматично репорт (private security disclosure) през GitHub.
https://docs.github.com/en/code-security/secure-coding/using-codeql-code-scanning-with-your-existing-ci-system/running-codeql-runner-in-your-ci-system#:~:text=The%20CodeQL%20runner%20is%20a%20command%2Dline%20tool%20that%20runs,scanning%20alerts%20in%20the%20repository.
=> Run security code scanning every morning

scripts/start-dev-db.sh
- Логваме всички заявки в локалния контейнер за базата
- Правим `npm run start:dev:db` скрипта работещ за Линукс.
=> Improve container db

src/violations/api/violations-statuses.controller.ts, src/violations/violations.module.ts
=> List violations statuses in an endpoint for admin filters

src/casl/casl-ability.factory.ts, src/protocols/api/protocols-statuses.controller.ts, src/protocols/entities/protocol.entity.ts, src/protocols/entities/protocols.repository.ts, src/protocols/protocols.module.ts
Добавя endpoint, които изброява всички възможни статуси на протоколите.
Свързано с https://github.com/ti-broish/admin/issues/32
=> List protocols statuses in an endpoint for admin filters

src/me/api/me-protocols.controller.ts, src/protocols/api/protocols-filters.dto.ts, src/protocols/api/protocols.controller.ts, src/protocols/entities/protocols.repository.ts, src/sections/api/section.dto.ts, src/sections/api/town.dto.ts, src/violations/api/violations-filters.dto.ts
Имплементира всички филтри в API-то за протоколите нужни за преброителния център.
Свързан с https://github.com/ti-broish/admin/issues/32
=> Филтри за протоколите в API

src/i18n/bg/origin.json, src/i18n/en/origin.json, src/protocols/api/protocols-origins.controller.ts, src/protocols/protocols.module.ts
Relates to: ti-broish/admin#32
=> Implement endpoint for listing all protocols origins with translations

src/streams/api/streams.controller.ts, src/streams/entities/stream.entity.ts
=> Use video service stream identifier for stopping

src/migrations/1625908967128-AddPublishedTextField.ts, src/violations/api/violation.dto.ts, src/violations/api/violations.controller.ts, src/violations/entities/violation-update.entity.ts, src/violations/entities/violation.entity.ts
* Създаване на нова миграция, която добавя колоната published_text към базата
* Записване на publishedText подадено в бодито към базата
Closes #
=> add publishedText column

src/protocols/api/protocol.dto.ts, src/protocols/api/protocols.controller.ts, src/sections/api/municipality.dto.ts, src/sections/api/section.dto.ts, src/sections/api/town.dto.ts, src/users/api/organization.dto.ts, src/users/api/user.dto.ts, src/violations/api/violation.dto.ts, src/violations/api/violations.controller.ts, src/violations/entities/violations.repository.ts
=> Фийд с публикувани сигнали

src/sections/api/municipality.dto.ts, src/sections/api/section.dto.ts, src/sections/api/town.dto.ts, src/streams/api/stream.dto.ts, src/streams/api/streams.controller.ts, src/streams/entities/streams.repository.ts
* Добавяне на фийд ендпойнт в стрийм контролера
* Създаване на метод, който взима само нецензурираните стриймове, които са лайв в момента и добавя паджинейшън
* Създаване на нова фийд група в стрийм
Closes #
=> add stream feed endpoint

src/pictures/api/picture.dto.ts, src/protocols/api/protocol-result.dto.ts, src/protocols/api/protocol.dto.ts, src/protocols/api/protocols.controller.ts, src/protocols/entities/protocols.repository.ts, src/results/api/results.controller.ts, src/sections/api/section.dto.ts, src/sections/api/town.dto.ts
* добавяне на протоколи със снимки към резултатите на секциите
* нов метод за взимане на протокол по секция 
Closes #
=> Add pictures section page

src/results/api/stats.dto.ts, src/sections/entities/sections.repository.ts
Добавяне на обработени и публикувани сигнали към статистиката на всеки сегмент
=> Add processed and published violations stats

src/results/api/results.controller.ts, src/results/api/stats.dto.ts, src/sections/entities/sections.repository.ts, src/sections/entities/towns.repository.ts
Добавяне на функционалност, която да брои и сигналите без секция, само с град
=> Add signals without sections stats

src/violations/entities/violations.repository.ts
* Групиране на идтата на сигналите, за да избегнем повторение заради ъпдейти
* ОПравяне на сегментирането, за да връща всички сигнали
=> fix segmentation and grouping

src/sections/entities/section.entity.ts, src/sections/entities/sections.repository.ts
*Добавяне на брой видеа към секция
*Добавяна на брой активни видеа към секция
Fixes #99
=> add stream count to stats for all segments

.github/dependabot.yml
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
=> Configure Dependabot PRs

.eslintrc.js, package.json, scripts/import-results.ts, src/app.module.ts, src/auth/auth-basic.strategy.ts, src/i18n/translate-status.interceptor.ts, src/protocols/entities/work-items.repository.ts, src/results/api/results.controller.ts, src/sections/entities/sections.repository.ts, src/users/api/user.dto.ts, src/utils/csvToSql.ts
Stricter linting, but some of the errors are converted to warnings for now
=> Update linting rules, ignore some warnings for now

src/auth/decorators/inject-firebase-user.decorator.ts, src/auth/decorators/inject-user.decorator.ts, src/auth/firebase.guard.ts, src/auth/firebase.strategy.ts, src/casl/casl-ability.factory.ts, src/casl/policies.guard.ts, src/me/api/me-clients.controller.ts, src/me/api/me-protocols.controller.ts, src/me/api/me-stream.controller.ts, src/me/api/me-violations.controller.ts, src/me/api/me.controller.ts, src/pictures/api/pictures.controller.ts, src/protocols/api/protocol-assignees.controller.ts, src/protocols/api/protocol-rejections.controller.ts, src/protocols/api/protocols-origins.controller.ts, src/protocols/api/protocols-statuses.controller.ts, src/protocols/api/protocols.controller.ts, src/sections/api/countries.controller.ts, src/sections/api/electionRegions.controller.ts, src/sections/api/sections.controller.ts, src/sections/api/towns.controller.ts, src/streams/api/streams.controller.ts, src/users/api/users-roles.controller.ts, src/users/api/users.controller.ts, src/violations/api/violation-assignees.controller.ts, src/violations/api/violation-comments.controller.ts, src/violations/api/violations-statuses.controller.ts, src/violations/api/violations.controller.ts
=> Публичен достъп до секциите

src/migrations/1676062972796-MakeActorIdViolationUpdatesOptional.ts, src/violations/api/violations.controller.ts, src/violations/entities/violation-update.entity.ts, src/violations/entities/violation.entity.ts
=> Deauth violations

src/migrations/1676252731919-MakeProtocolActionsActorOptional.ts, src/protocols/api/protocols.controller.ts, src/protocols/entities/protocol-action.entity.ts, src/protocols/entities/protocol.entity.ts, src/protocols/entities/protocols.repository.ts
=> Протоколи без аутентикация

src/migrations/1676411442647-MakeOrganizationsIsHiddenDefaultToBoolean.ts
Оправя сийдването на организации след 01c892d69d09aadd553d0b614a2164f5ccd98e23
Вече [organization seed-а](https://github.com/ti-broish/api/blob/b7fe9e8bb2ef3a31c6afc0f9eed47623532b8ae8/src/seeds/1607157753776-Organizations.ts) работи коректно. След 01c892d69d09aadd553d0b614a2164f5ccd98e23, сиийдът е създавал всички организации като скрити.
=> Оправяне на сийдването на организации

src/sections/entities/sections.repository.ts
Оправя филтъра на секции по градски район след промените в https://github.com/ti-broish/api/commit/2df5c806547006bc3f7fa3225c82a9c37717539f?diff=split#diff-048f7e591be533625a92e1340a80264b215129e81d38a71004fc63a29f6d0180
=> Fix sections filter by city region filter using query builder

src/protocols/api/protocol.dto.ts, src/protocols/entities/protocol.entity.ts, src/protocols/entities/protocols.repository.ts
Follow-up to https://github.com/ti-broish/api/pull/157 and relates to https://github.com/ti-broish/admin/pull/71
=> Fix protocol section replacement and loading

src/migrations/1676594664001-AddSectionsRiskyLevel.ts, src/results/api/results.controller.ts, src/results/api/stats.dto.ts, src/sections/api/section.dto.ts, src/sections/entities/section.entity.ts, src/sections/entities/sections.repository.ts
Closes #161 
Добавяне на отбелязване за рискови секции в резултатите, които картата може да използва за ti-broish/results#50
=> Add risk level to sections

docs/admin-api-endpoints.txt, docs/api-flow.txt, src/i18n/bg/status.json, src/i18n/en/status.json, src/users/api/user.dto.ts
=> Clean up remaining code for broadcast of notifications

src/protocols/entities/work-items.repository.ts
Closes #134 
No longer we need to fetch a bigger batch and shuffle them. This would eliminate the race condition when multiple people are picking up protocols.
=> Use postgres pessimistic lock when picking items from the queue

package-lock.json, package.json, src/app.module.ts
=> Remove unused @nestjs/schedule package after removing broadcasts

src/protocols/api/protocols.controller.ts, src/protocols/api/work-queue.service.ts, src/protocols/entities/work-items.repository.ts
Оправя 500 грешка при опит за взимане на протокол от опашката.
=> Fix usage of pessimistic lock in queue by adding transactions

package-lock.json, package.json, src/casl/casl-ability.factory.ts, src/migrations/1677621951298-AddSectionsPopulation.ts, src/results/api/stats.dto.ts, src/sections/api/section.dto.ts, src/sections/api/sections.controller.ts, src/sections/entities/section.entity.ts, src/sections/entities/sections.repository.ts, src/sections/population.parser.ts
Relates to ti-broish/results#51
=> Add stats for population of sections

src/results/api/crumb-maker.service.ts, src/results/api/results.controller.ts, src/sections/api/sections.controller.ts, src/sections/entities/cityRegion.entity.ts, src/sections/entities/country.entity.ts, src/sections/entities/electionRegion.entity.ts, src/sections/entities/electionRegions.repository.ts, src/sections/entities/municipalities.repository.ts, src/sections/entities/municipality.entity.ts, src/sections/entities/section.entity.ts, src/sections/entities/sections.repository.ts, src/sections/entities/towns.repository.ts, src/sections/entities/withCode.interface.ts, src/sections/sections.constants.ts, src/streams/api/streams.controller.ts
Оптимизира доста заявките за резултатите като:
=> Optimise section and partial section matching with relations

src/i18n/bg/errors.json, src/i18n/en/errors.json, src/i18n/i18n-exceptions.filter.ts, src/protocols/api/protocol-assignees.controller.ts, src/protocols/api/protocol.dto.ts, src/protocols/api/protocols.controller.ts, src/protocols/entities/protocol-action.entity.ts, src/protocols/entities/protocol.entity.ts, src/protocols/entities/protocol.exceptions.ts, src/streams/api/streams-webhook.controller.ts, src/streams/api/streams.controller.ts, src/violations/api/violation-assignees.controller.ts
Частта за протоколи от #185
```
PATCH /protocols/:id/contact
{
"email": "john.doe@example.com"
}
202 Accepted
```
=> Приемане на email след създаване на протокол

src/violations/api/violation.dto.ts, src/violations/api/violations.controller.ts, src/violations/entities/violation-update.entity.ts, src/violations/entities/violation.entity.ts
=> Приемане на сигнал с данни за контакт

src/i18n/bg/protocol.json, src/i18n/en/protocol.json, src/protocols/entities/protocol.entity.ts
=> Oбновяване на причините за отхвърляне на протокол

src/casl/casl-ability.factory.ts, src/sections/api/section.dto.ts, src/sections/api/sections.controller.ts, src/sections/api/town.dto.ts, src/sections/entities/section.entity.ts, src/sections/entities/sections.repository.ts
=> Allow creating section in existing localities from validators

src/files/files-uploader.service.ts, src/pictures/pictures-uploader.service.ts
Изтриване на снимката от локалния сторидж след запазване в минио
Closes #
36
=> Deletes picture after its added to storage
