package.json

It is not needed since lint-staged 10.0 and warns about it since a few versions ago

Remove obsolete git add from lint-staged

---

.github/workflows/build.yml
.github/workflows/pr.yml
package.json

- Leave GitHub Actions checkout ref by default
- Lint code in CI without fixingit, but just reporting violations

Improve GitHub Workflows with forks support and linting

---

package.json
src/seeds/1616992561879-AddStreams.ts

Подобрява първоначалния setup при пускането на seeds.
Преди имаше проблем, тъй като не се копираше seeds папката в dist освен ако не се пусне `npm run build`, за да стартира `postbuild` скрипта.
Seed-а за видеостриймовете даваше грешка, ако липсват CSV данните. Сега само показва warning.

Fix seeds first run

---

src/sections/api/town-exists.constraint.ts
src/sections/api/town.dto.ts
src/sections/entities/sections.repository.ts
src/sections/entities/towns.repository.ts
src/violations/api/violations-filters.dto.ts
src/violations/entities/violations.repository.ts

Градовете са едно от последните неща от локациите и секциите, за които в публичния интерфейс (REST API) не използваме познати публични кодове, а всъщност разкривахме вътрешни идентификатори.
Това всъщност въвежда използването на [ЕКАТТЕ кодовете на градовете в България](https://bg.m.wikipedia.org/wiki/%D0%95%D0%9A%D0%90%D0%A2%D0%A2%D0%95) и би позволило синхронизация и на кодовете на градовете в чужбина.
Това би улеснило няколко неща в бъдеще:
✅  Консистентност - всички endpoints свързани със секциите ще използват външно познати идентификатори.
✅  Консистентност - и резултатите и endpoints за секции и други за филтри в админа ще ползват едни и същи идентификатори. Досега само резултатите използваха ЕКАТТЕ кодовете на градовете.
✅  Интеграции - По този начин можем да се интегрираме …

Номенклатурни кодове на градовете вместо вътрешни идентификатори

---

.eslintrc.js
src/i18n/bg/status.json
src/i18n/en/status.json
src/migrations/1624337501383-AddTownsCountryMunicipalityIndices.ts
src/sections/api/town-exists.constraint.ts
src/sections/api/town.dto.ts
src/sections/entities/town.entity.ts
src/sections/sections.module.ts
src/users/api/organization-exists.constraint.ts
src/users/api/user-exists.constraint.ts
src/utils/ulid-constraint.ts
src/violations/api/violation.dto.ts
src/violations/api/violations-filters.dto.ts
src/violations/api/violations.controller.ts
src/violations/entities/violations.repository.ts
src/violations/violations.module.ts

Предоставя филтри в API-то за сигналите, които могат да се използват от клиента на преброителния център.
Добавя всички филтри нужни за https://github.com/ti-broish/admin/issues/33 и оправя няколко неща като валидации и достъп до списъка с филтри.

Филтри за сигналите в преброителния център

---

src/violations/api/violation-comments.controller.ts

Изискваме пълен достъп до сигналите в администрацията дори за да имаш достъп, за да четеш коментарите към сигнал. Иначе може и да се заобиколи контрола на достъп до сигналите.

Require full access to violations in order to even read violation commments

---

src/users/api/users-filters.dto.ts
src/users/api/users.controller.ts
src/users/entities/users.repository.ts
src/violations/api/violations.controller.ts

Добавени са филтри за потребителите като по име, фамилия и имейл може да се търси с част от съвпадението.
Relates to https://github.com/ti-broish/admin/issues/35

Add users filters

---

src/protocols/api/protocols.controller.ts
src/users/api/users.controller.ts
src/utils/pagination-route.ts
src/violations/api/violation-comments.controller.ts
src/violations/api/violations.controller.ts

`links` in the pagination responses didn't work properly before as it ignored any query param filters. With this, it will omit the current page query param, keep the rest and then the pagination library would add the correct page at the end. So there will be no duplicate page params either.

Generate correct links in pagination with query params

---

src/violations/entities/violations.repository.ts

Досега не връщахме assignes към сигнал в отговора от API-то когато филтрираме по assignee. Когато не филтрираме, ги имаше и преди.

Return violations assignees in admin even when filtering by assignee

---

src/utils/page.dto.ts

Вместо трансформация без валидация е по-добре да валидираме `page` параметъра.
Това също оправя грешната `@Optional` декорация. Валидационната декорация е `@IsOptional`.

Validate page query param properly

---

src/checkins/api/checkin.dto.ts
src/checkins/checkins.module.ts
src/checkins/entities/checkin.entity.ts
src/checkins/entities/checkins.repository.ts
src/me/api/me-checkins.controller.ts
src/me/me.module.ts
src/migrations/1625092684710-CreateTableCheckins.ts
src/users/entities/user.entity.ts

Дава възможност на потребилите на мобилното приложение - застъпници, представители и секционни членове да се отбележат в секцията в момента, в който пристигнат, за да имам видимост за разпределението по места и проблеми с логването в приложението, които да коригираме своевременно.
Това също би позволило по-бърз достъп до започване на видеопоток, изпращане на сигнал или на протокол от тази секция без да се минава отново през селектора на секция.
Заявка:
```
POST /me/checkins
{
"section": "071200004"
}
```
Отговор:
```json
{
"id": "01F9FJK6TCTZPRNA4BA707FFQE",
"section": {
"id": "071200004"
},
"timestamp": "2021-06-30T20:03:20.146Z"
}
```
Списък:

Add POST /me/checkins for checking in a section as early as possible

---

src/migrations/1625594972743-AddOrganizationsSortPosition.ts
src/users/entities/organization.entity.ts

Добавя поле за ред на организациите.
This help with migrating users from organizations across campaigns as
previously we were using the primary key for sorting which is also
a foreign key in the people table and is harder to modify freely.

Order organizations by a custom sort position

---

src/migrations/1625607338385-AlterStreamIdentiferLength.ts
src/streams/api/stream-censor.service.ts
src/streams/api/streams.controller.ts
src/streams/entities/streams.repository.ts
src/streams/streams.module.ts

Follow-up to #73.
This is better in order to keep our controllers thin, have more, but simpler and named steps in the code and make the service reusable for the `Users#update` action.

Extract Stream Censor as a service

---

src/casl/role.enum.ts
src/config/schema.config.ts
src/config/swagger.config.ts
src/i18n/bg/errors.json
src/i18n/en/errors.json
src/migrations/1625609333009-AddWorkItems.ts
src/migrations/1625635791732-MakeWorkItemsProtocolAssigneeUnique.ts
src/protocols/api/protocol-assignees.controller.ts
src/protocols/api/protocols.controller.ts
src/protocols/api/work-queue.service.ts
src/protocols/entities/protocol.entity.ts
src/protocols/entities/protocols.repository.ts
src/protocols/entities/work-item.entity.ts
src/protocols/entities/work-items.repository.ts
src/protocols/protocols.module.ts
src/users/entities/user.entity.ts

Подменя имплементацията на опашката за валидиране на протоколи
Вече вместо динамична опашка имаме статична опашка от протоколи в базата с данни.
Контролира се при записване на протокол вместо при четене.
Когато се получи протокол се въвеждат N на брой "work items", които се приоритизират на база на bitmask от условия.
Цели:
- Да постигнем двойна (или повече) валидация на един и същ протокол от няколко валидатора паралелно. Съответно ни е нужна по-голяма гъвкавост колко хора валидират един протокол без да се повтарят.
- Да постигнем по-полезно приоритизиране на протоколите в опашката без да правим много сложни при взимане от опашката.
- Да запазим auditability на действията - кой кога е взимал, връщал и валидирал протокол.
- Всички досегашни endpoints за валидиране да продължат да работят …

Работна опашка за валидиране

---

src/sections/entities/sections.repository.ts
src/violations/api/violations.controller.ts
src/violations/entities/violations.repository.ts

Добавяне на ендпойнт функционалност за филтриране на фийда от сигнали по сегмент
Closes #95

Add filtering feed violations

---

src/firebase/auth/passport-firebase.strategy.ts
src/me/api/me.controller.ts

Когато аутентикацията е успешна, не прекъсваме процеса, а продължаваме към отбелязване на невъзможност да се идентифицира потребител, което логва мистериозната грешка в логовете, че човек, който е успял да се логне, всъщност не е успял.

Fix auth bug

---

src/migrations/1676413609314-MakeProtocolsSectionOptional.ts
src/protocols/api/protocol.dto.ts
src/protocols/api/protocols.controller.ts
src/protocols/entities/protocol.entity.ts
src/protocols/entities/protocols.repository.ts

Closes #103 
Позволява изпращане на протоколи без посочване на секция и преглеждането им в преброителния център.
В същото време запазва backwards compatibility с мобилните приложения, които могат да продължат да изпращат секцията.

Протоколи без секция

---

src/sections/api/section.dto.ts
src/sections/api/sections.controller.ts
src/sections/api/town.dto.ts
src/sections/entities/country.entity.ts

Това е нужно за ti-broish/admin#68
Closes #186 
Преизползвам направеното в #189, за да връщам данните за локацията на една секция когато тя липсва.
API-то ще връща 404 когато секцията липсва, но ако има секция със същите първи 6 знака ще връща данните за държавата, МИР-а и общината. Данните за града няма как да са със сигурност същите, но структурата ще се запази и общината ще се показва през полето за град, дори да няма данни за град.
<table>
<thead>
<tr>
<th>section</th>
<th>response status code</th>
<th>response body</th>
<th>notes</th>
</tr>
</thead>
<tbody>
<tr>
<td>
`010100002`
</td>
<td>
`200`
</td>
<td>
```json
{
"code": "002",
"electionRegion": {
"code": "01",
"isAbroad": false,
"name": "Благоевград"
},
"id": "010100002",
"isMachine": null,
"isMobile": false,
"place": "ПЛТГ \"Н. …
```

Връщане на локация при липсваща секция

---

src/protocols/api/protocol.dto.ts
src/protocols/entities/protocol.entity.ts

Това помага за ti-broish/admin#65
Добавя всички нови полета нужни за бланката на протокола в новата кампания.
---
Досега не приемахме в АPI-то всички възможни полета, но сега искаме да имаме всяко число, което го има на бланката, не само за проверки във фронтенда (ti-broish/admin#67), но и за автоматично разпознаване на проблеми в бакенда и генериране на сигнал #139

Всички полета от протокола в АPI-то

---

scripts/import-results.ts
src/migrations/1678817237783-DropProtocolDataTable.ts

Oт известно време вече, ползваме колоната `protocols.metadata` в `jsonb` формат.
`ProtocolData` се използва само като `ValueObject` и се напасва в `ProtocolDto`, не е entity както беше преди.

Remove unused protocol_data table

---

src/sections/entities/sections.repository.ts

Връщаме обратно табулацията на резултатите в API-то, което беше скрито, за да не бави когато имахме само сигнали.

Връщане табулацията на резултатите

---

src/auth/decorators/allow-only-firebase-user.decorator.ts
src/auth/decorators/index.ts
src/auth/firebase.guard.ts
src/casl/casl-ability.factory.ts
src/firebase/auth/passport-firebase.strategy.ts
src/migrations/1679015326884-AddSecretToProtocolsAndViolations.ts
src/protocols/api/protocol.dto.ts
src/protocols/api/protocols.controller.ts
src/protocols/entities/protocol.entity.ts
src/users/api/registration.service.ts
src/users/api/users.controller.ts
src/violations/api/violation.dto.ts
src/violations/api/violations.controller.ts
src/violations/entities/violation.entity.ts

Свързано с ti-broish/results#86
С тези промени, след изпращане на протокол или сигнал, в отговора от сървъра ще се съдържа парола в `secret` полето. Тази парола е достъпна само и единствено непосредствено след създаването на протокола/сигнала.
Тази парола може да бъде запазена в `localStorage` и да се използва за достъпване на протокол или сигнал.
Така протоколите и сигналите са защитени, но все пак могат да бъдат достъпени използвайки запазената парола за съответния протокол/сигнал и авторът може да проследи статуса след като са ги подали.
`GET /protocols/:protocol?secret=:secret`
`GET /violations/:violation?secret=:secret`

Достъп до протокол/сигнал без регистрация, но с парола

---

docs/api-flow.txt
src/migrations/1679441168487-ChangeCountriesTo3LetterCode.ts
src/protocols/api/protocols-filters.dto.ts
src/protocols/entities/protocols.repository.ts
src/results/api/results.controller.ts
src/sections/entities/country.entity.ts
src/sections/entities/sections.repository.ts
src/sections/sections-pattern.ts
src/sections/sections.constants.ts
src/violations/api/violations-filters.dto.ts
src/violations/api/violations.controller.ts
src/violations/entities/violations.repository.ts

Closes #214 
На база решение на ЦИК: https://www.cik.bg/bg/decisions/1666/2023-02-15
Секциите извън страната вече използват различна номерация на държавите с 3 цифри.
С тези промени променяме засичането на номерата на секциите така че да поддържа различната номерация в България и извън страната
- Би трябвало да се деплойне без проблеми дори със съществуващи секции извън страната заради включените миграции. Но първо ще тестваме как се държи с картата за резултатите, която има покритие и рискови секции.
Като следваща стъпка можем да налеем новите секции извън страната.

Държави с 3-цифрен код
